@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "us:UserStorage" as US
participant "u:User" as U
participant "method:Refund" as RE <<Interface>>
participant "r:Reservation" as R

[-> S + : refund(u_id, r_id, method: Refund)
    S -> US + : refund(u_id, r_id, method)
        US -> U + : refund(r_id, method)
            U -> RE + : refund(&r)
            loop ["as needed"]
                RE -> R + : query
                deactivate R
            end
            U <-- RE - : Ok
        US <-- U - : Ok
    S <-- US - : Ok
[<-- S - : Ok

@enduml