@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "rs:ReservationStorage" as RS <<Interface>>
participant "method:Refund" as RE <<Interface>>
participant "r:Reservation" as R
participant "us:UserStorage" as US <<Interface>>
participant "u:User" as U

[-> S + : refund(u_id, r_id, method: Refund)
    S -> RS + : act_on(u_id, r_id, method)
        RS -> R + : expect u_id == user_id()
        deactivate R
        RS -> RE + : refund(&r)
            loop ["as needed"]
            RE -> R + : do_something
            deactivate R
            end
        RS <-- RE - : refunded: Money
    S <-- RS - : refunded

    S -> US + : withdraw(u_id, r_id)
        US -> U + : withdraw(r_id)
        deactivate U
    deactivate US
[<-- S - : Ok



@enduml