@startuml

package Domain {
    package Sessions {
        interface ReserveTicketsSession {
            +start_reservation(&mut self, user_id: Strg_clientg) -> ReservationId;
            +add(&mut self, token: ItemToken) -> Result<()>;
            +remove(&mut self, token: ItemToken) -> Result<()>;
            +summary(&self, token: ItemToken) -> Result<Strg_clientg>;
            +confirm(&mut self, token: UserToken) -> Result<()>;
            +abort(&mut self, token: UserToken) -> Result<()>;
            +pay(&mut self, token: UserToken) -> Result<()>;
        }
    }

    package Storage {
        interface UserStorage


    }

    ReserveTicketsSession ..> UserStorage
}

@enduml