@startuml

hide footbox
autonumber "<b>##."

actor "u:User" as U
participant "s:System" as S

opt ["independent entry"]
U -> S : refundable_reservations(u_id)
U <-- S : all available reservations
end
U -> S : start_refund(u_id, r_id)
U -> S : reason
U <-- S : success / failure




@enduml