@startuml

left to right direction

package FlightReservationSystem {
    (Login) as L
    package Core {
        (ViewFlights) as V
        (ReserveTickets) as RT
        (Pay) as P

        RT -left- P : involves
    }
    (Refund) as R
}

Actor User as U

U -- L
U -- RT
U -- R
U -- V


@enduml