@startuml

left to right direction

package FlightReservationSystem {
    (Login) as L
    package Core {
        (ViewFlights) as V
        (ReserveTickets) as RT
        (Withdraw) as W

        (Pay) as P
        (View Profile) as VP

        RT -- P : involves
    }
    (Refund) as R
}

Actor User as U

U -- L
U -- RT
U -- R
U -- V
U -- W
U -- VP


@enduml