@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "active_reservations\n:ReservationStorage" as AR <<Interface>>
participant "r:Reservation" as R

[-> S + : abort(u_id, r_id)
    S -> AR + : unsafe { extract(u_id, r_id) }
    S <-- AR - : r: Reservation
    S -> R ! : drop
[<-- S - : Ok
@enduml