@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "is:ItemStorage" as IS
participant "ar:ActiveReservationStorage" as AR
participant "r:Reservation" as R

[-> S + : add(u_id, r_id, item_id)
    S -> IS + : occupy(item_id)
    S <-- IS - : Ok
    S -> AR + : authenticated_add(u_id, r_id, item_id)
        AR -> R + : expect u_id == user_id()
        AR -> R : add(item_id)
        AR <-- R - : Ok
    S <-- AR - : Ok
[<-- S - : Ok

@enduml