@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "pending_reservations\n:ReservationStorage" as PR <<Interface>>
participant "p:Payment" as P <<Interface>>
participant "r:Reservation" as R
participant "us:UserStorage" as US <<Interface>>
participant "u:User" as U

[-> S + : pay(u_id, r_id, p: Payment)
    S -> PR + : act_on(u_id, r_id, p)
        PR -> R + : expect u_id == user_id()
        deactivate R
        PR -> P + : pay(&r)
            loop ["as need"]
                P --> R + : do something
                deactivate R
            end
        PR <-- P - : paid: Money
    S <-- PR - : paid

    S ->> US + : link(u_id, r_id)
        US -> U + : link(r)
        deactivate U
    deactivate US
[<-- S - : Ok


@enduml