@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "us:UserStorage" as US <<Interface>>
participant "active_reservations\n:CreativeReservationStorage" as AR <<Interface>>
participant "rf:ReservationFactory" as RF <<Interface>>

[-> S + : start_reservation(user_id)
    S -> US + : user_exists(user_id)
    S <-- US - : true
    S -> AR + : new_reservation(user_id)
        AR -> RF + : with_user_id(user_id)
        create "r:Reservation" as R
        RF --> R : create
        AR <-- RF - : r: Reservation
    S <-- AR - : r_id: ReservationId
[<-- S - : r_id


@enduml