@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "us:UserStorage" as US
participant "rf:ReservationFactory" as RF

[-> S + : start_reservation(user_id)
    S -> US + : user_exists(user_id)
    S <-- US - : true
    S -> US + : start_reservation(user_id)
        US -> RF + : with_user_id(user_id)
            create "r:Reservation" as R
            RF --> R : create
        US <-- RF - :  r: Reservation
        US -> US : store(r)
        participant "u:User" as U
        US -> U + : link(r_id: ReservationId)
        US <-- U - : ok
    S <-- US - : r_id
[<-- S - : r_id


@enduml