@startuml

hide footbox
autonumber "<b>##."

participant "s:Session" as S
participant "us:UserStorage" as US
participant "ar:ActiveReservationStorage" as AR
participant "rf:ReservationFactory" as RF

' TODO: Law of Demeter

[-> S + : start_reservation(user_id)
    S -> US + : user_exists(user_id)
    S <-- US - : true
    S -> AR + : new_reservation(user_id)
        AR -> RF + : with_user_id(user_id)
        create "r:Reservation" as R
        RF --> R : create
        AR <-- RF - : r: Reservation
    S <-- AR - : r_id: ReservationId
[<-- S - : r_id
note bottom
    Note that the reservation is temporarily stored in
    ar:ActiveReservationStorage. It is not until `confirm`
    is called that the reservation will be eventually
    stored into persistent storages and linked with the
    user.
end note


@enduml